package ionix.Data.SqlServer;

import ionix.Data.*;
import ionix.Utils.Ext;
import ionix.Utils.Triplet;

import java.lang.reflect.Field;
import java.util.HashSet;
import java.util.List;

public class BatchCommandInsert<TEntity> extends ionix.Data.BatchCommandInsert<TEntity>  {

    public BatchCommandInsert(Class<TEntity> entityClass, TransactionalDbAccess dataAccess){
        super(entityClass, dataAccess);
    }

    @Override
    protected ionix.Data.EntitySqlQueryBuilderInsert createInsertBuilder(){
        return new ionix.Data.SqlServer.EntitySqlQueryBuilderInsert();
    }

    @Override
    protected int getMetaDataSize(EntityMetaData metaData, Triplet<SqlQuery, AutoGeneratedKey, FieldMetaData> result){
        int metaDataSize = this.getInsertFields() == null ? metaData.size() : this.getInsertFields().size();
        FieldMetaData identity = result.Item3;
        if (metaDataSize > 1 && null != identity)
            --metaDataSize;
        return metaDataSize;
    }
}
